workspace_roots = [
    "~/workspace/personal",
    "~/workspace/work",
]
default_shell = "zsh"
plugin_timeout = 30
default_select_by = "workspace"
on_enter = "tmux"
on_create = "tmux"

[selector]
backend = "fzf"

[fzf]
height = "90%"

[plugins]
enabled = [
    "git-worktree",
    "tmux",
]

[plugin_settings]

[[session_name_stages]]
name = "prefix"
kind = "choice"
choices = [
    "feat",
    "fix",
    "chore",
]

[[session_name_stages]]
name = "ticket-prefix"
kind = "choice"
choices = ["PROJ"]

[[session_name_stages]]
name = "ticket-number"
kind = "text"
choices = []
